flights:
  day_range: 1
  flight_order: DESC
  one_way: 1
  round_trip: 2
  max_seat: 100
  min_seat: 9
bookings:
  normal_class: "A"
  business_class: "B"
  normal_seat: 1
  business_seat: 2
  fixed_money: 2
  minimum_total_price: 0
  pending: 1
  success: 2
time:
  past: 200
  future: 1
payment_methods:
  cash: "Cash"
validations:
  user:
    min_age: 10
    email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
    phone_regex: !ruby/regexp '/\A[0-9]{7,11}\z/'
    name_minlength: 5
    name_maxlength: 50
    email_minlength: 5
    email_maxlength: 255
    phone_minlength: 7
    phone_maxlength: 11
    password_minlength: 6
    password_maxlength: 15    
test:
  default_password: "123456"
  default_phone: "0977860499"
  default_seat_number: 100
